version: '3'
services:
  jenkins:
    container_name: master
    build: .
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./.ssh/id_rsa:/var/jenkins_home/.ssh/id_rsa
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    links:
     - slave01

  slave01:
    container_name: slave01
    build: ./slave
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=${JENKINS_SLAVE_SSH_PUBKEY}
