version: '3'
services:
  jenkins:
    container_name: master
    image: jenkins/jenkins:lts
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./.ssh/id_rsa:/var/jenkins_home/.ssh/id_rsa
    ports:
      - 8080:8080
    links:
     - slave01

  slave01:
    container_name: slave01
    build: ./slave
    volumes:
      - ./slave/workspace:/home/jenkins/workspace
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=${JENKINS_SLAVE_SSH_PUBKEY}
