version: '3'

services:
  jenkins:
    container_name: master
    build: .
    volumes:
      - ./jenkins_home:/var/jenkins_home
      # - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    links:
      - rbenv-slave
      - docker-host
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

  rbenv-slave:
    container_name: rbenv-slave
    build: ./rbenv-slave
    volumes:
      - rbenv:/opt/rbenv
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=${JENKINS_SLAVE_SSH_PUBKEY}

  # tcp://docker-host:2375
  docker-host:
    container_name: docker-host
    image: docker:dind
    volumes:
      - docker:/var/lib/docker
    privileged: true

volumes:
  rbenv:
    driver: local
  docker:
    driver: local
