version: '3'

services:
  jenkins:
    container_name: master
    build: .
    volumes:
      - ./jenkins_home:/var/jenkins_home
      # - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    links:
      - rbenv-slave
      - docker-host
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

  # tcp://docker-host:2375
  docker-host:
    container_name: docker-host
    build: ./docker-host
    privileged: true
    volumes:
      - docker:/var/lib/docker
    links:
      - docker-registry

  docker-registry:
    container_name: docker-registry
    image: registry
    volumes:
      - registry:/var/lib/registry 
    ports:
      - 5000:5000

volumes:
  docker:
    driver: local
  registry:
    driver: local
