version: '3'

services:
  jenkins:
    container_name: master
    build: .
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # set env COMPOSE_CONVERT_WINDOWS_PATHS=1 for windows
    ports:
      - 8080:8080
    links:
      - slave
      - docker-host
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

  slave:
    container_name: slave
    image: jenkinsci/ssh-slave
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=${JENKINS_SLAVE_SSH_PUBKEY}

  # tcp://docker-host:2375
  docker-host:
    container_name: docker-host
    image: docker:18.09.9-dind
    command: --insecure-registry docker-registry:5000
    privileged: true
    volumes:
      - docker:/var/lib/docker
    links:
      - docker-registry

  docker-registry:
    container_name: docker-registry
    image: registry
    volumes:
      - registry:/var/lib/registry

volumes:
  docker:
    driver: local
  registry:
    driver: local
