version: '3.3'

services:
  master:
    container_name: master
    build: ./master
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./casc_configs:/var/jenkins_conf
      - /var/run/docker.sock:/var/run/docker.sock # set env COMPOSE_CONVERT_WINDOWS_PATHS=1 for windows
    ports:
      - 8080:8080
    secrets:
      - jenkins_slave_ssh_private_key
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_conf
      - SLAVE_AGENT_PORT=${SLAVE_AGENT_PORT}

  # Jenkins slave settings
  #   Host Key Verification Strategy: Non verifying Vertification Strategy
  #   Environment:
  #     JAVA_HOME: /usr/local/openjdk-8
  ssh-slave:
    container_name: ssh-slave
    image: jenkinsci/ssh-slave:v1.0.0
    depends_on:
      - master
    env_file:
      - ssh-slave.env

  jnlp-slave:
    container_name: jnlp-slave
    image: jenkinsci/jnlp-slave:3.36-2
    depends_on:
      - master
    volumes:
      - ./wait-for-it:/wait-for-it
    entrypoint: /wait-for-it/wait-for-it.sh -t 0 master:${SLAVE_AGENT_PORT} -- jenkins-agent
    env_file:
      - jnlp-slave.env
    environment:
      - JENKINS_URL=http://master:8080
      - JENKINS_AGENT_NAME=jnlp-slave

  docker-host-slave:
    container_name: docker-host-slave
    build: ./docker-host-slave
    depends_on:
      - master
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock # set env COMPOSE_CONVERT_WINDOWS_PATHS=1 for windows
    env_file:
      - ssh-slave.env

  # tcp://docker-host:2375
  docker-host:
    container_name: docker-host
    image: docker:18.09.9-dind
    command: --insecure-registry docker-registry:5000
    privileged: true
    volumes:
      - docker:/var/lib/docker
    links:
      - docker-registry

  docker-registry:
    container_name: docker-registry
    image: registry
    volumes:
      - registry:/var/lib/registry
    ports:
      - 5000:5000

volumes:
  docker:
    driver: local
  registry:
    driver: local

secrets:
  jenkins_slave_ssh_private_key:
    file: .ssh/id_rsa
